name: bricks
description: Package Storage for Flutter Developer
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  _file:
    path: local_packages/_file
  _photo:
    path: local_packages/_photo
  _tinder_swipe:
    path: local_packages/_tinder_swipe
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.6
  provider: ^6.0.5

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
