name: bricks
description: Package Storage for Flutter Developer
version: 0.1.0
homepage: 'https://github.com/congson99/bricks'
publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  _file:
    path: bricks/_file
  _photo:
    path: bricks/_photo
  _button:
    path: bricks/_button
  _textfield:
    path: bricks/_textfield
  _avatar:
    path: bricks/_avatar

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/brick/
    - assets/images/
